encoding: utf-8
port: 5678
host: 0.0.0.0

title: Deshaun
keywords: [放飞自我，学习]
description: '还是要看清自己'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
# plugins: [jekyll-paginate, jemoji]
plugins: [jekyll-paginate]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
# emoji:
#     src: 'https://api.fooleap.org'
paginate: 10
repository: i-znan/i-znan.github.io

nickname: Deshaun
home: https://shaun.github.io
# api: https://api.fooleap.org
# IMG_PATH: //source.fooleap.org
IMG_PATH: /img
tongji: '9bb4bf149fca98f317e75329260f7961'
analytics: 'UA-139257940-1'

# Comments  disqus needs vpn
disqus_username: Deshaun
